export const lists = {
  "Personal Interests": [
    "Animals Give Back",
    "Antiquing",
    "Archery",
    "Armed Services Give Back",
    "Astronomy",
    "Baking",
    "Ballroom Dancing",
    "Baseball",
    "Baseball Fan",
    "Basketball",
    "Basketball Fan",
    "Beekeeping",
    "Bird watching",
    "Blogging",
    "Boating",
    "Book Club",
    "Bowling",
    "Boxing",
    "Bridge",
    "Camping",
    "Car Refurbishing/Collecting",
    "Ceramics",
    "Chess",
    "Coaching Sports",
    "Commonwealth Special Service Award Winner",
    "Community Activism",
    "Cooking",
    "Crafts",
    "Creative Writing",
    "Crossfit",
    "Dance",
    "Disaster Relief and Environmental Give Back",
    "Dog Lover",
    "Entertaining",
    "Environmental Responsibility",
    "Faith Based Give Back",
    "Family and Human Services Give Back",
    "Fencing",
    "Fine Art",
    "Fishing",
    "Flower Arranging",
    "Fly Fishing",
    "Flying",
    "Food and Drink",
    "Gardening",
    "Golf",
    "Grandparenting",
    "Health and Wellness Give Back",
    "Hiking",
    "Hockey Fan",
    "Horseback Riding",
    "Hunting",
    "Interior Design",
    "Jewelry making",
    "Journaling",
    "Kayaking",
    "Kick Boxing",
    "Knitting",
    "Live music",
    "Martial Arts",
    "Meditation",
    "Motorcycling",
    "Mountain biking",
    "NASCAR",
    "Non-Profit Boards",
    "Nutrition",
    "Painting/Drawing",
    "Parenting",
    "Peloton",
    "Performance training",
    "Photography",
    "Pilates",
    "Playing music",
    "Podcasts",
    "Poverty and Hunger Give Back",
    "Quilting",
    "Racquetball",
    "Reading – Fiction",
    "Reading – Non-Fiction",
    "Real Estate",
    "Road Biking",
    "Rock climbing",
    "Rowing",
    "Running",
    "Sailing",
    "Singing",
    "Skiing",
    "Snow Boarding",
    "Soccer",
    "Soccer Fan",
    "SUP",
    "Surfing",
    "Survival Skills",
    "Swimming",
    "Tai Chi",
    "Tennis",
    "Theater",
    "Traveling",
    "Veteran",
    "Volleyball",
    "Walking",
    "Weightlifting",
    "Woodworking",
    "Writing",
    "Yoga",
    "Youth and Education Give Back"
  ],
  "Business Interests": [
    "2nd Generation Clients",
    "401Ks",
    "Advanced Planning topics",
    "Best Practices",
    "Business Continuity",
    "Business transitions: I need a continuity partner",
    "Business transitions: I would like to buy a practice",
    "Business transitions: I'm thinking about selling my practice",
    "Career Paths",
    "Charitable Giving Strategies",
    "Client Events",
    "Client Experience",
    "Client reviews",
    "Compensation/equity strategies",
    "Continuity Planning",
    "Economic Trends",
    "Estate Law Changes",
    "Family Offices",
    "Fee Structure",
    "Financial Planning",
    "Giving Back",
    "Goal Setting",
    "Growth through referrals",
    "Growth/Business Development",
    "Hiring an advisor",
    "Human Resources",
    "Investment Ideas",
    "Investment Strategies",
    "Marketing/Social Media",
    "Mentoring the next gen",
    "Mergers and Acquisitions",
    "Networking",
    "Niche Partnerships",
    "Operational Efficiency",
    "Options",
    "P360 Models",
    "Pensions",
    "Personal Development",
    "Picking stocks",
    "Portfolio Management",
    "PR Strategies",
    "Practice Management",
    "Process Improvement",
    "Retirement Income Planning",
    "Retirement Planning",
    "RIA",
    "Small Business Owners",
    "Small Practice",
    "Social Media",
    "Staff Development",
    "Study Groups",
    "Succession Planning",
    "Tax Law Changes",
    "Tax Strategies",
    "Team Building",
    "Technology Super User",
    "Transitioning Practice to next generation",
    "Working with seniors",
    "Working with strategic alliances"
  ],
  "Job Responsibilities": [
    "Anticipate advisor's needs and handle proactively",
    "Assist with investment decisions (such as portfolio construction, asset allocation, and rebalancing)",
    "Assist with marketing campaigns",
    "Assist with projects, as needed",
    "Completing client paperwork",
    "Complying with all FINRA/SEC/Commonwealth compliance regulations",
    "Conduct client review meetings",
    "Conduct investment research",
    "Conduct monthly/quarterly/ad hoc client reporting",
    "Coordinate client events",
    "Coordinate production and mailing of client newsletter",
    "Create & execute business plan",
    "Create & execute marketing plan",
    "Create and manage internal workflows",
    "Create and update procedures manual",
    "Create personal financial statements",
    "Developing and sustaining relationships with strategic alliances (CPAs, attorneys, etc.)",
    "Generate client reports",
    "Generating and pursuing new client opportunities",
    "Greeting clients",
    "Handling client phone calls",
    "Input data into financial planning software",
    "Keep abreast of industry trends",
    "Maintain brochures and firm stationery",
    "Maintain client cost basis information",
    "Maintain client gift program",
    "Maintain client records in CRM",
    "Manage and update firms website",
    "Manage staff",
    "Meet with clients to review paperwork to ensure accuracy",
    "Organizing and maintaining client financial documents",
    "Oversee compliance",
    "Perform general office duties (such as filing, sorting mail, typing correspondence)",
    "Perform mail merges",
    "Prepare client correspondence",
    "Prepare for client meetings",
    "Presenting at prospect meetings",
    "Recommend plans and products to help clients achieve goals",
    "Research new products and services",
    "Review client statements",
    "schedule meetings for advisors",
    "Set marketing deadlines",
    "Track and order office supplies",
    "Track pending business paperwork",
    "Trade in client accounts",
    "Train staff",
    "Upload documents"
  ],
  "Business Niche": [
    "Doctors and dentists",
    "LBGT Clients",
    "Millennials",
    "Pharmaceutical/Tech executives",
    "Retirement plans",
    "Small business owners",
    "Teachers",
    "Women in transition",
    "Working with family members",
    "Working with people with special needs"
  ]
};
