export const lists = {
  "Personal Interests": [
    "Baseball",
    "Basketball",
    "Bird watching",
    "Blogging",
    "Boating",
    "Callighraphy",
    "Career Coach",
    "Cato Institute Ideas",
    "Charitable causes",
    "Chess",
    "Classical Music",
    "Cooking",
    "Crafts",
    "Creative Writing",
    "Cricket",
    "Cross Country Skiing",
    "Crossword puzzles",
    "Dancing",
    "Down Hill Skiing",
    "Environmental responsibility",
    "Fine Art",
    "Fishing",
    "Food and Drink",
    "Football",
    "Gardening",
    "Giving Back",
    "Golf",
    "Grandparenting",
    "Gym Cardio",
    "Hiking",
    "Hockey",
    "Hunting",
    "Kayaking",
    "Knitting",
    "Life Coach",
    "Live music",
    "Meditation",
    "Mountain biking",
    "Nature",
    "Non-Profit Boards",
    "Nutrition",
    "Painting/Drawing",
    "Parenting",
    "Personal retirement readiness",
    "Philanthropy",
    "Photography",
    "Pickle Ball",
    "Playing music/Singing",
    "Podcasts",
    "Pottery",
    "Quilting",
    "Real Estate",
    "Road Biking",
    "Rock Climbing",
    "Running",
    "Scrapbooking",
    "Singing",
    "Skydiving",
    "Snowboarding",
    "Soccer",
    "Special Service Award Winner",
    "Spiritual Beliefs/Religion/Faith",
    "Squash",
    "Tennis",
    "Theater",
    "Traveling",
    "Veteran",
    "Video games",
    "Volunteering",
    "Wake Surfing",
    "Weightlifting",
    "Wood working",
    "Writing",
    "Yoga"
  ],
  "Business Interests": [
    "2nd Generation Clients",
    "401Ks",
    "Advanced Planning topics",
    "Best Practices",
    "Business Continuity",
    "Career Paths",
    "CFP",
    "Charitable Giving Strategies",
    "Client Events",
    "Client Experience",
    "Client reviews",
    "Compensation/equity strategies",
    "Continuity Planning",
    "Economic Trends",
    "Ensemble evolution",
    "Hiring an advisor",
    "Mentoring the next gen",
    "Business transitions: I need a continuity partner",
    "Business transitions: I'm thinking about selling my practice",
    "Business transitions: I would like to buy a practice",
    "Estate Law Changes",
    "Family Offices",
    "Fee Structure",
    "Financial Planning",
    "Goal Setting",
    "Growth through referrals",
    "Growth/Business Development",
    "Human Resources",
    "Investment Ideas",
    "Investment Strategies",
    "Marketing/Social Media",
    "Mergers and Acquisitions",
    "Networking",
    "Niche Partnerships",
    "Operational Efficiency",
    "Options",
    "P360 Models",
    "Pensions",
    "Personal Development",
    "Picking stocks",
    "Portfolio Management",
    "PR Strategies",
    "Practice Management",
    "Process Improvement",
    "Retirement Income Planning",
    "Retirement Planning",
    "RIA",
    "Social Media",
    "Small Business Owners",
    "Small Practice",
    "Staff Development",
    "Study Groups",
    "Succession Planning",
    "Tax Law Changes",
    "Tax Strategies",
    "Team Building",
    "Technology Super User",
    "Transitioning Practice to next generation",
    "Working with seniors",
    "Working with strategic alliances"
  ],
  "Job Responsibilities": [
    "Completing client paperwork",
    "Handling client phone calls",
    "Track pending business paperwork",
    "Greeting clients",
    "Generate client reports",
    "Maintain client records in CRM",
    "Coordinate client events",
    "Prepare client correspondence",
    "Prepare for client meetings",
    "Assist with marketing campaigns",
    "Track and order office supplies",
    "Create and manage internal workflows",
    "Manage staff",
    "Train staff",
    "Create and update procedures manual",
    "Upload documents",
    "Perform general office duties (such as filing, sorting mail, typing correspondence)",
    "Organizing and maintaining client financial documents",
    "Assist with investment decisions (such as portfolio construction, asset allocation, and rebalancing)",
    "Maintain client cost basis information",
    "Conduct onthly/quarterly/ad hoc client reporting",
    "Conduct investment research",
    "Review client statements",
    "Create personal financial statements",
    "Keep abreast of industry trends",
    "Input data into financial planning software",
    "Conduct client review meetings",
    "Recommend plans and products to help clients achieve goals",
    "Create & execute business plan",
    "Create & execute marketing plan",
    "Oversee compliance",
    "schedule meetings for advisors",
    "Assist with projects, as needed",
    "Manage and update firms website",
    "Maintain client gift program",
    "Set marketing deadlines",
    "Perform mail merges",
    "Maintain brochures and firm stationery",
    "Coordinate production and mailing of client newsletter",
    "Meet with clients to review paperwork to ensure accuracy",
    "Research new products and services",
    "Trade in client accounts",
    "Generating and pursuing new client opportunities",
    "Presenting at prospect meetings",
    "Developing and sustaining relationships with strategic alliances (CPAs, attorneys, etc.)",
    "Complying with all FINRA/SEC/Commonwealth compliance regulations",
    "Anticipate advisor's needs and handle proactively"
  ],
  "Business Niche": [
    "Working with family members",
    "Teachers",
    "Millennials",
    "Women in transition",
    "Retirement plans",
    "Doctors and dentists",
    "Pharmaceutical/Tech executives",
    "Small business owners",
    "LBGT Clients"
  ]
};
